apiVersion: v1 
kind: configMap
metadata: 
 name: shipping-configmap 
 namespace: roboshop
 labels:
    project: roboshop
    tier: backend
    component: shipping
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: shipping 
  namespace: roboshop
  labels: 
    project : roboshop
    component: shipping 
    tire: backend    
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      project : roboshop
      component: shipping 
      tire: backend   
  template: 
    metadata:
      labels: 
        project : roboshop
        component: shipping 
        tire: backend          
    spec:
     containers:
      - name : shipping
        image: taruntejamb/shipping:1.0.0
        imagePullPolicy: Always 
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 256Mi
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          failureThreshold: 2
          periodSeconds: 10  
        envFrom:
         - configMapRef:
            name: shipping-config 

---
apiVersion: v1 
kind: Service 
metadata:
 name: shipping 
 namespace: roboshop 
 labels: 
   project : roboshop
   component: shipping 
   tire: backend   
spec:
 selector: 
   project : roboshop
   component: shipping 
   tire: backend    
 ports: 
  - protocol: TCP
    port: 8080 
    targetPort: 8080